// <auto-generated>
// This file has been generated by ConsoleTests.tt from TAEF_Console.csv - do not edit it, but edit the CSV file and
// regenerate this file (see ConsoleTests.tt).
// </auto-generated>

using Microsoft.VisualStudio.TestTools.UnitTesting;
using TaefTestAdapter.Tests.Common;
using static TaefTestAdapter.Tests.Common.TestMetadata.TestCategories;

namespace TaefTestAdapter.VsPackage
{
    [TestClass]
    public partial class ConsoleDllTests : AbstractConsoleTests
    {

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTests_SlnProjSettings_Cov_Iso()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"SolutionProject",
                TestCaseFilter = @"none",
                EnableCodeCoverage = true,
                InIsolation = true,
                RunInProcess = false,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTests_Settings_Type_EQ_Small()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"true",
                TestCaseFilter = @"Type=Small",
                EnableCodeCoverage = false,
                InIsolation = false,
                RunInProcess = false,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void NEG_SampleTests_Cov_NotExisting_EQ_Foo()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"false",
                TestCaseFilter = @"*NotExisting=Foo",
                EnableCodeCoverage = true,
                InIsolation = false,
                RunInProcess = false,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTests_Iso_DisplayName_EQ_TaefSamples_TestMath_AddPassesWithTraits()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"false",
                TestCaseFilter = @"DisplayName=TaefSamples::TestMath::AddPassesWithTraits",
                EnableCodeCoverage = false,
                InIsolation = true,
                RunInProcess = false,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void HardCrashingSampleTests()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"HardCrashingSampleTests",
                Settings = @"false",
                TestCaseFilter = @"none",
                EnableCodeCoverage = false,
                InIsolation = false,
                RunInProcess = false,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTests_Settings_Cov_InProc_Rep2_DisplayName_EQ_TaefSamples_3e2140d3()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"true",
                TestCaseFilter = @"DisplayName=TaefSamples::TestMath::AddPassesWithTraits",
                EnableCodeCoverage = true,
                InIsolation = false,
                RunInProcess = true,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 2
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTests_Settings_Iso_RunIgn_ClassLevel_TestCategory_EQ_NotExisting()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"true",
                TestCaseFilter = @"TestCategory=NotExisting",
                EnableCodeCoverage = false,
                InIsolation = true,
                RunInProcess = false,
                RunIgnoredTests = @"true",
                IsolationLevel = @"Class",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTests_Cov_Iso_MethodLevel_Type_EQ_Small()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"false",
                TestCaseFilter = @"Type=Small",
                EnableCodeCoverage = true,
                InIsolation = true,
                RunInProcess = false,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Method",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTests_Cov_Iso_InProc_SkipIgn_DisplayName_EQ_TaefSamples_0339a593()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"false",
                TestCaseFilter = @"DisplayName=TaefSamples::TestMath::AddPassesWithTraits|Type=Small",
                EnableCodeCoverage = true,
                InIsolation = true,
                RunInProcess = true,
                RunIgnoredTests = @"false",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTests_Settings_Iso_SkipIgn_MethodLevel_Rep2_TestCategory_15149d31()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"true",
                TestCaseFilter = @"TestCategory=Integration&Type=Medium",
                EnableCodeCoverage = false,
                InIsolation = true,
                RunInProcess = false,
                RunIgnoredTests = @"false",
                IsolationLevel = @"Method",
                NrOfTestRepetitions = 2
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTests_Cov_RunIgn_TestCategory_EQ_Integration_AND_Type_EQ_Medium()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"false",
                TestCaseFilter = @"TestCategory=Integration&Type=Medium",
                EnableCodeCoverage = true,
                InIsolation = false,
                RunInProcess = false,
                RunIgnoredTests = @"true",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void HardCrashingSampleTests_Settings_Cov_Iso_ClassLevel()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"HardCrashingSampleTests",
                Settings = @"true",
                TestCaseFilter = @"none",
                EnableCodeCoverage = true,
                InIsolation = true,
                RunInProcess = false,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Class",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void HardCrashingSampleTests_SlnSettings_InProc()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"HardCrashingSampleTests",
                Settings = @"Solution",
                TestCaseFilter = @"none",
                EnableCodeCoverage = false,
                InIsolation = false,
                RunInProcess = true,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void HardCrashingSampleTestsX64_Iso_InProc()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"HardCrashingSampleTestsX64",
                Settings = @"false",
                TestCaseFilter = @"none",
                EnableCodeCoverage = false,
                InIsolation = true,
                RunInProcess = true,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void HardCrashingSampleTestsX64_SlnProjSettings_Cov_ClassLevel()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"HardCrashingSampleTestsX64",
                Settings = @"SolutionProject",
                TestCaseFilter = @"none",
                EnableCodeCoverage = true,
                InIsolation = false,
                RunInProcess = false,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Class",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void NEG_SampleTests_SlnSettings_Iso_NotExisting_EQ_Foo()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"Solution",
                TestCaseFilter = @"*NotExisting=Foo",
                EnableCodeCoverage = false,
                InIsolation = true,
                RunInProcess = false,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTests_SlnSettings_Ignore_EQ_true()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"Solution",
                TestCaseFilter = @"Ignore=true",
                EnableCodeCoverage = false,
                InIsolation = false,
                RunInProcess = false,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTests_SlnProjSettings_InProc_ClassLevel_Ignore_EQ_true()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"SolutionProject",
                TestCaseFilter = @"Ignore=true",
                EnableCodeCoverage = false,
                InIsolation = false,
                RunInProcess = true,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Class",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTests_Cov_RunIgn_Rep2_Ignore_EQ_true()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"false",
                TestCaseFilter = @"Ignore=true",
                EnableCodeCoverage = true,
                InIsolation = false,
                RunInProcess = false,
                RunIgnoredTests = @"true",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 2
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTestsX64_Settings_DisplayName_EQ_TaefSamples_TestMath_150abafa()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTestsX64",
                Settings = @"true",
                TestCaseFilter = @"DisplayName=TaefSamples::TestMath::AddPassesWithTraits|Type=Small",
                EnableCodeCoverage = false,
                InIsolation = false,
                RunInProcess = false,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTestsX64_SlnProjSettings_Cov_Iso_InProc()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTestsX64",
                Settings = @"SolutionProject",
                TestCaseFilter = @"none",
                EnableCodeCoverage = true,
                InIsolation = true,
                RunInProcess = true,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTestsX64_Iso_ClassLevel_FQN_CONTAINS_NamedRows()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTestsX64",
                Settings = @"false",
                TestCaseFilter = @"FullyQualifiedName~NamedRows",
                EnableCodeCoverage = false,
                InIsolation = true,
                RunInProcess = false,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Class",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTests_SlnProjSettings_RunIgn_FQN_EQ_TaefSamples_TestMath_03b9743a()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"SolutionProject",
                TestCaseFilter = @"FullyQualifiedName=TaefSamples.TestMath.AddPassesWithTraits",
                EnableCodeCoverage = false,
                InIsolation = false,
                RunInProcess = false,
                RunIgnoredTests = @"true",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void DllTests_Settings()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"DllTests",
                Settings = @"true",
                TestCaseFilter = @"none",
                EnableCodeCoverage = false,
                InIsolation = false,
                RunInProcess = false,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void DllTests_Cov_Iso_InProc_ClassLevel()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"DllTests",
                Settings = @"false",
                TestCaseFilter = @"none",
                EnableCodeCoverage = true,
                InIsolation = true,
                RunInProcess = true,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Class",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTests()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"false",
                TestCaseFilter = @"none",
                EnableCodeCoverage = false,
                InIsolation = false,
                RunInProcess = false,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTestsX64_SlnSettings_Cov_MethodLevel_Rep2_Type_EQ_Small()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTestsX64",
                Settings = @"Solution",
                TestCaseFilter = @"Type=Small",
                EnableCodeCoverage = true,
                InIsolation = false,
                RunInProcess = false,
                RunIgnoredTests = @"default",
                IsolationLevel = @"Method",
                NrOfTestRepetitions = 2
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTests_Settings_InProc_SkipIgn_FQN_CONTAINS_NamedRows()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTests",
                Settings = @"true",
                TestCaseFilter = @"FullyQualifiedName~NamedRows",
                EnableCodeCoverage = false,
                InIsolation = false,
                RunInProcess = true,
                RunIgnoredTests = @"false",
                IsolationLevel = @"Default",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void SampleTestsX64_SlnSettings_Cov_Iso_SkipIgn_ClassLevel_Ignore_EQ_true()
        {
            RunConsoleTest(new ConsoleTestCase
            {
                TestFile = @"SampleTestsX64",
                Settings = @"Solution",
                TestCaseFilter = @"Ignore=true",
                EnableCodeCoverage = true,
                InIsolation = true,
                RunInProcess = false,
                RunIgnoredTests = @"false",
                IsolationLevel = @"Class",
                NrOfTestRepetitions = 1
            });
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void List_TestsOf_SampleTests()
        {
            ListFullyQualifiedTestsOf(@"SampleTests");
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void List_TestsOf_HardCrashingSampleTests()
        {
            ListFullyQualifiedTestsOf(@"HardCrashingSampleTests");
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void List_TestsOf_HardCrashingSampleTestsX64()
        {
            ListFullyQualifiedTestsOf(@"HardCrashingSampleTestsX64");
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void List_TestsOf_SampleTestsX64()
        {
            ListFullyQualifiedTestsOf(@"SampleTestsX64");
        }

        [TestMethod]
        [TestCategory(EndToEnd)]
        public void List_TestsOf_DllTests()
        {
            ListFullyQualifiedTestsOf(@"DllTests");
        }

    }
}
