// 5000 test methods TaefSamples::LoadTests::Test0 ... TaefSamples::LoadTests::Test4999 (the tests with an odd number pass).
//
// The test methods are generated by the preprocessor (no code generator needed): LOAD_TEST_<n> creates the test
// with the n-digit number given as single digits, the LOAD_TESTS_* macros create groups of 10 and 100 tests.
// Real test methods (instead of one data-driven method) make discovery, symbol lookup (5000 functions in the PDB)
// and test selection (/select with thousands of names) as expensive as possible.
#include "WexTestClass.h"

#define LOAD_TEST(name, number) TEST_METHOD(Test##name) { VerifyIsOdd(number); }

#define LOAD_TEST_1(a)          LOAD_TEST(a, a)
#define LOAD_TEST_2(a, b)       LOAD_TEST(a##b, a * 10 + b)
#define LOAD_TEST_3(a, b, c)    LOAD_TEST(a##b##c, a * 100 + b * 10 + c)
#define LOAD_TEST_4(a, b, c, d) LOAD_TEST(a##b##c##d, a * 1000 + b * 100 + c * 10 + d)

// Test0 .. Test9
#define LOAD_TESTS_1() \
    LOAD_TEST_1(0) LOAD_TEST_1(1) LOAD_TEST_1(2) LOAD_TEST_1(3) LOAD_TEST_1(4) \
    LOAD_TEST_1(5) LOAD_TEST_1(6) LOAD_TEST_1(7) LOAD_TEST_1(8) LOAD_TEST_1(9)

// Test<a>0 .. Test<a>9
#define LOAD_TESTS_2(a) \
    LOAD_TEST_2(a, 0) LOAD_TEST_2(a, 1) LOAD_TEST_2(a, 2) LOAD_TEST_2(a, 3) LOAD_TEST_2(a, 4) \
    LOAD_TEST_2(a, 5) LOAD_TEST_2(a, 6) LOAD_TEST_2(a, 7) LOAD_TEST_2(a, 8) LOAD_TEST_2(a, 9)

// Test<a><b>0 .. Test<a><b>9
#define LOAD_TESTS_3(a, b) \
    LOAD_TEST_3(a, b, 0) LOAD_TEST_3(a, b, 1) LOAD_TEST_3(a, b, 2) LOAD_TEST_3(a, b, 3) LOAD_TEST_3(a, b, 4) \
    LOAD_TEST_3(a, b, 5) LOAD_TEST_3(a, b, 6) LOAD_TEST_3(a, b, 7) LOAD_TEST_3(a, b, 8) LOAD_TEST_3(a, b, 9)

// Test<a>00 .. Test<a>99
#define LOAD_TESTS_3_100(a) \
    LOAD_TESTS_3(a, 0) LOAD_TESTS_3(a, 1) LOAD_TESTS_3(a, 2) LOAD_TESTS_3(a, 3) LOAD_TESTS_3(a, 4) \
    LOAD_TESTS_3(a, 5) LOAD_TESTS_3(a, 6) LOAD_TESTS_3(a, 7) LOAD_TESTS_3(a, 8) LOAD_TESTS_3(a, 9)

// Test<a><b><c>0 .. Test<a><b><c>9
#define LOAD_TESTS_4(a, b, c) \
    LOAD_TEST_4(a, b, c, 0) LOAD_TEST_4(a, b, c, 1) LOAD_TEST_4(a, b, c, 2) LOAD_TEST_4(a, b, c, 3) LOAD_TEST_4(a, b, c, 4) \
    LOAD_TEST_4(a, b, c, 5) LOAD_TEST_4(a, b, c, 6) LOAD_TEST_4(a, b, c, 7) LOAD_TEST_4(a, b, c, 8) LOAD_TEST_4(a, b, c, 9)

// Test<a><b>00 .. Test<a><b>99
#define LOAD_TESTS_4_100(a, b) \
    LOAD_TESTS_4(a, b, 0) LOAD_TESTS_4(a, b, 1) LOAD_TESTS_4(a, b, 2) LOAD_TESTS_4(a, b, 3) LOAD_TESTS_4(a, b, 4) \
    LOAD_TESTS_4(a, b, 5) LOAD_TESTS_4(a, b, 6) LOAD_TESTS_4(a, b, 7) LOAD_TESTS_4(a, b, 8) LOAD_TESTS_4(a, b, 9)

namespace TaefSamples
{
    class LoadTests
    {
        TEST_CLASS(LoadTests)

        static void VerifyIsOdd(int number)
        {
            VERIFY_ARE_EQUAL(1, number % 2);
        }

        // Test0 .. Test99
        LOAD_TESTS_1()
        LOAD_TESTS_2(1) LOAD_TESTS_2(2) LOAD_TESTS_2(3) LOAD_TESTS_2(4) LOAD_TESTS_2(5) LOAD_TESTS_2(6) LOAD_TESTS_2(7) LOAD_TESTS_2(8) LOAD_TESTS_2(9)

        // Test100 .. Test999
        LOAD_TESTS_3_100(1)
        LOAD_TESTS_3_100(2)
        LOAD_TESTS_3_100(3)
        LOAD_TESTS_3_100(4)
        LOAD_TESTS_3_100(5)
        LOAD_TESTS_3_100(6)
        LOAD_TESTS_3_100(7)
        LOAD_TESTS_3_100(8)
        LOAD_TESTS_3_100(9)

        // Test1000 .. Test4999
        LOAD_TESTS_4_100(1, 0) LOAD_TESTS_4_100(1, 1) LOAD_TESTS_4_100(1, 2) LOAD_TESTS_4_100(1, 3) LOAD_TESTS_4_100(1, 4)
        LOAD_TESTS_4_100(1, 5) LOAD_TESTS_4_100(1, 6) LOAD_TESTS_4_100(1, 7) LOAD_TESTS_4_100(1, 8) LOAD_TESTS_4_100(1, 9)
        LOAD_TESTS_4_100(2, 0) LOAD_TESTS_4_100(2, 1) LOAD_TESTS_4_100(2, 2) LOAD_TESTS_4_100(2, 3) LOAD_TESTS_4_100(2, 4)
        LOAD_TESTS_4_100(2, 5) LOAD_TESTS_4_100(2, 6) LOAD_TESTS_4_100(2, 7) LOAD_TESTS_4_100(2, 8) LOAD_TESTS_4_100(2, 9)
        LOAD_TESTS_4_100(3, 0) LOAD_TESTS_4_100(3, 1) LOAD_TESTS_4_100(3, 2) LOAD_TESTS_4_100(3, 3) LOAD_TESTS_4_100(3, 4)
        LOAD_TESTS_4_100(3, 5) LOAD_TESTS_4_100(3, 6) LOAD_TESTS_4_100(3, 7) LOAD_TESTS_4_100(3, 8) LOAD_TESTS_4_100(3, 9)
        LOAD_TESTS_4_100(4, 0) LOAD_TESTS_4_100(4, 1) LOAD_TESTS_4_100(4, 2) LOAD_TESTS_4_100(4, 3) LOAD_TESTS_4_100(4, 4)
        LOAD_TESTS_4_100(4, 5) LOAD_TESTS_4_100(4, 6) LOAD_TESTS_4_100(4, 7) LOAD_TESTS_4_100(4, 8) LOAD_TESTS_4_100(4, 9)
    };
}
