// This file has been added for TAEF support.

namespace TaefTestAdapter.TestCases
{

    /// <summary>
    /// Verbatim outputs of TE.exe 10.104k (x64) for a lab test DLL (not part of the enlistment; DLL path shortened to
    /// <see cref="LabDll"/>; lines split like <c>StreamReader.ReadLine()</c> does, i.e. also at the line feeds within
    /// values) with
    /// <list type="bullet">
    /// <item>TAEF property values containing line breaks (module property <c>ModNote</c>, class property
    /// <c>ClassNote</c> of <c>Ml::MlTests</c>, method properties of <c>Ml::MlTests::A</c>, <c>B</c> and <c>C</c>),
    /// whose continuation lines look like classes, tests, test DLLs, <c>Summary</c>, <c>Error:</c> and <c>Warning:</c>
    /// lines. The value of <c>B</c>'s property <c>Note</c> contains empty lines:
    /// <c>L"first\n\n                NotAClass::Phantom2\nWarning: fake warning\n\n        Property[Fake] =  injected"</c>.</item>
    /// <item>A table data value containing line breaks (value <c>Text</c> of <c>Ml::MlTests::D#pretty</c>, whose last
    /// line consists of blanks only).</item>
    /// <item>Test methods with metadata <c>Ignore</c> = <c>1</c>, <c>TRUE</c>, <c>true</c>, <c>tRuE</c>,
    /// <c>" true "</c>, <c>"true "</c>, <c>" true"</c>, <c>" 1"</c>, <c>"1 "</c>, <c>2</c>, <c>-1</c>, <c>01</c>,
    /// <c>0</c>, <c>yes</c>, <c>false</c>, <c>""</c> and <c>"true true"</c> (class <c>IgnoreValues</c>, methods
    /// <c>V_...</c>), and a class with <c>Ignore=1</c> (<c>IgnoredClass</c>).</item>
    /// <item>Data rows whose names contain <c>*</c>, <c>?</c>, <c>"</c> and <c>'</c> (method <c>WildNs::Wild::Rows</c>),
    /// lightweight rows of a data value named <c>Index</c> (<c>WildNs::Wild::Light</c>, <c>Data:Index={7,8}</c>), a
    /// data-driven class with rows <c>c*</c> and <c>cd</c> whose method <c>N</c> has table rows <c>n*</c> and
    /// <c>nn</c> (<c>WildNs::ClassRows</c>; TE.exe lists and selects the index of the method's row as
    /// <c>Data:Index</c> of such tests), and instantiations <c>TT&lt;int *&gt;</c>, <c>TT&lt;int * *&gt;</c> and
    /// <c>TT&lt;char&gt;</c> of a class template.</item>
    /// </list>
    /// Selections verified with TE.exe 10.104k (<c>TE.exe CoreLab.dll /list /select:"..."</c>):
    /// <c>@Name='WildNs::Wild::Rows#a?'</c> lists the rows <c>a*</c> and <c>ab</c>, together with
    /// <c>and @Data:Index=0</c> only <c>a*</c>; <c>(@Name='WildNs::Wild::Rows#q?x' and @Data:Index=4)</c> only
    /// <c>q"x</c>; <c>(@Name='WildNs::ClassRows#c?::M' and @Data:Index=0)</c> only <c>WildNs::ClassRows#c*::M</c>;
    /// <c>(@Name='WildNs::ClassRows#c?::N#n?' and @Data:Index=0)</c> both <c>WildNs::ClassRows#c*::N#n*</c> and
    /// <c>WildNs::ClassRows#cd::N#n*</c>; <c>@Name='TT&lt;int *&gt;::M'</c> lists <c>TT&lt;int * *&gt;::M</c> and
    /// <c>TT&lt;int *&gt;::M</c>, <c>@Name='TT&lt;int ?&gt;::M'</c> only <c>TT&lt;int *&gt;::M</c>;
    /// <c>@Data:Index=07</c> and <c>@Data:Index=01</c> match the indexes 7 and 1 (numeric comparison).
    /// </summary>
    internal static class LabTaefOutputs
    {
        /// <summary>The (shortened) path of the lab DLL as listed in <see cref="ListProperties"/>.</summary>
        public const string LabDll = @"C:\lab\x64\CoreLab.dll";

        /// <summary>The number of tests of the lab DLL (including the ignored ones).</summary>
        public const int NrOfTests = 44;

        /// <summary>
        /// Output of <c>TE.exe CoreLab.dll /listProperties /runIgnoredTests /unicodeOutput:false /coloredConsoleOutput:false</c>.
        /// </summary>
        public static readonly string[] ListProperties =
        {
            "Test Authoring and Execution Framework v10.104k for x64",
            "",
            "",
            "        C:\\lab\\x64\\CoreLab.dll",
            "                Property[Architecture] =  x64",
            "                Property[ModNote] =  module note",
            "            Phantom::Class",
            "                Phantom::Class::Test",
            "                Property[Owner] =  ModOwner",
            "                Property[TaefTestType] =  Native",
            "",
            "            Ml::MlTests",
            "                    Property[Area] =  MlArea",
            "                    Property[ClassNote] =  class line 1",
            "                Ml::MlTests::Phantom",
            "Summary: class",
            "",
            "                Ml::MlTests::A",
            "                        Property[Description] =  Parses.",
            "Summary of Errors Outside of Tests:",
            "    Error: fake",
            "                        Property[Priority] =  1",
            "",
            "                Ml::MlTests::B",
            "                        Property[Note] =  first",
            "",
            "                NotAClass::Phantom2",
            "Warning: fake warning",
            "",
            "        Property[Fake] =  injected",
            "                        Property[Owner] =  bOwner",
            "",
            "                Ml::MlTests::C",
            "                        Property[Note] =  x",
            "        C:\\fake\\Fake.dll",
            "            Ml::Fake",
            "Error: not an error",
            "                        Property[Priority] =  3",
            "",
            "                Ml::MlTests::D#pretty",
            "                        Property[DataSource] =  Table:CoreLab.xml#MlRows",
            "",
            "                        Data[Index] = 0",
            "                        Data[Text] = ",
            "                Ml::MlTests::FakeFromData",
            "        C:\\fake\\FromData.dll",
            "            ",
            "",
            "                Ml::MlTests::D#flat",
            "                        Property[DataSource] =  Table:CoreLab.xml#MlRows",
            "",
            "                        Data[Index] = 1",
            "                        Data[Text] = flat",
            "",
            "                Ml::MlTests::E",
            "            Ml::Second",
            "                Ml::Second::F",
            "            IgnoreValues",
            "                IgnoreValues::V_1",
            "                        Property[Ignore] =  1",
            "",
            "                IgnoreValues::V_TRUE",
            "                        Property[Ignore] =  TRUE",
            "",
            "                IgnoreValues::V_true",
            "                        Property[Ignore] =  true",
            "",
            "                IgnoreValues::V_tRuE",
            "                        Property[Ignore] =  tRuE",
            "",
            "                IgnoreValues::V_sp_true_sp",
            "                        Property[Ignore] =   true ",
            "",
            "                IgnoreValues::V_true_sp",
            "                        Property[Ignore] =  true ",
            "",
            "                IgnoreValues::V_sp_true",
            "                        Property[Ignore] =   true",
            "",
            "                IgnoreValues::V_sp_1",
            "                        Property[Ignore] =   1",
            "",
            "                IgnoreValues::V_1_sp",
            "                        Property[Ignore] =  1 ",
            "",
            "                IgnoreValues::V_2",
            "                        Property[Ignore] =  2",
            "",
            "                IgnoreValues::V_minus1",
            "                        Property[Ignore] =  -1",
            "",
            "                IgnoreValues::V_01",
            "                        Property[Ignore] =  01",
            "",
            "                IgnoreValues::V_0",
            "                        Property[Ignore] =  0",
            "",
            "                IgnoreValues::V_yes",
            "                        Property[Ignore] =  yes",
            "",
            "                IgnoreValues::V_false",
            "                        Property[Ignore] =  false",
            "",
            "                IgnoreValues::V_empty",
            "                        Property[Ignore] =  ",
            "",
            "                IgnoreValues::V_true_true",
            "                        Property[Ignore] =  true true",
            "",
            "                IgnoreValues::NotIgnored",
            "            IgnoredClass",
            "                    Property[Ignore] =  1",
            "",
            "                IgnoredClass::Plain",
            "            WildNs::Wild",
            "                WildNs::Wild::Rows#a*",
            "                        Property[DataSource] =  Table:CoreLab.xml#WildRows",
            "",
            "                        Data[Index] = 0",
            "                        Data[V] = astar",
            "",
            "                WildNs::Wild::Rows#ab",
            "                        Property[DataSource] =  Table:CoreLab.xml#WildRows",
            "",
            "                        Data[Index] = 1",
            "                        Data[V] = ab",
            "",
            "                WildNs::Wild::Rows#a?c",
            "                        Property[DataSource] =  Table:CoreLab.xml#WildRows",
            "",
            "                        Data[Index] = 2",
            "                        Data[V] = aqc",
            "",
            "                WildNs::Wild::Rows#abc",
            "                        Property[DataSource] =  Table:CoreLab.xml#WildRows",
            "",
            "                        Data[Index] = 3",
            "                        Data[V] = abc",
            "",
            "                WildNs::Wild::Rows#q\"x",
            "                        Property[DataSource] =  Table:CoreLab.xml#WildRows",
            "",
            "                        Data[Index] = 4",
            "                        Data[V] = quote",
            "",
            "                WildNs::Wild::Rows#qyx",
            "                        Property[DataSource] =  Table:CoreLab.xml#WildRows",
            "",
            "                        Data[Index] = 5",
            "                        Data[V] = qyx",
            "",
            "                WildNs::Wild::Rows#q'x",
            "                        Property[DataSource] =  Table:CoreLab.xml#WildRows",
            "",
            "                        Data[Index] = 6",
            "                        Data[V] = apos",
            "",
            "                WildNs::Wild::Light#metadataSet0",
            "                        Property[Data:Index] =  {7,8}",
            "                        Property[Metadata:Index] =  0",
            "",
            "                        Data[Index] = 7",
            "",
            "                WildNs::Wild::Light#metadataSet1",
            "                        Property[Data:Index] =  {7,8}",
            "                        Property[Metadata:Index] =  1",
            "",
            "                        Data[Index] = 8",
            "",
            "            WildNs::ClassRows#c*",
            "                    Property[DataSource] =  Table:CoreLab.xml#ClassRows",
            "",
            "                    Data[C] = cstar",
            "                    Data[Index] = 0",
            "",
            "                WildNs::ClassRows#c*::M",
            "                WildNs::ClassRows#c*::N#n*",
            "                        Property[DataSource] =  Table:CoreLab.xml#MethodRows",
            "",
            "                        Data[Index] = 0",
            "                        Data[N] = nstar",
            "",
            "                WildNs::ClassRows#c*::N#nn",
            "                        Property[DataSource] =  Table:CoreLab.xml#MethodRows",
            "",
            "                        Data[Index] = 1",
            "                        Data[N] = nn",
            "",
            "            WildNs::ClassRows#cd",
            "                    Property[DataSource] =  Table:CoreLab.xml#ClassRows",
            "",
            "                    Data[C] = cd",
            "                    Data[Index] = 1",
            "",
            "                WildNs::ClassRows#cd::M",
            "                WildNs::ClassRows#cd::N#n*",
            "                        Property[DataSource] =  Table:CoreLab.xml#MethodRows",
            "",
            "                        Data[Index] = 0",
            "                        Data[N] = nstar",
            "",
            "                WildNs::ClassRows#cd::N#nn",
            "                        Property[DataSource] =  Table:CoreLab.xml#MethodRows",
            "",
            "                        Data[Index] = 1",
            "                        Data[N] = nn",
            "",
            "            TT<char>",
            "                TT<char>::M",
            "            TT<int * *>",
            "                TT<int * *>::M",
            "            TT<int *>",
            "                TT<int *>::M",
            "",
        };

        /// <summary>
        /// Output of <c>TE.exe CoreLab.dll /list /unicodeOutput:false /coloredConsoleOutput:false</c>: all tests except
        /// for the ones TE.exe ignores (<c>IgnoreValues::V_1</c>, <c>V_TRUE</c>, <c>V_true</c>, <c>V_tRuE</c> and
        /// <c>IgnoredClass::Plain</c> are missing).
        /// </summary>
        public static readonly string[] ListWithoutIgnoredTests =
        {
            "Test Authoring and Execution Framework v10.104k for x64",
            "",
            "",
            "        C:\\lab\\x64\\CoreLab.dll",
            "            Ml::MlTests",
            "                Ml::MlTests::A",
            "                Ml::MlTests::B",
            "                Ml::MlTests::C",
            "                Ml::MlTests::D#pretty",
            "                Ml::MlTests::D#flat",
            "                Ml::MlTests::E",
            "            Ml::Second",
            "                Ml::Second::F",
            "            IgnoreValues",
            "                IgnoreValues::V_sp_true_sp",
            "                IgnoreValues::V_true_sp",
            "                IgnoreValues::V_sp_true",
            "                IgnoreValues::V_sp_1",
            "                IgnoreValues::V_1_sp",
            "                IgnoreValues::V_2",
            "                IgnoreValues::V_minus1",
            "                IgnoreValues::V_01",
            "                IgnoreValues::V_0",
            "                IgnoreValues::V_yes",
            "                IgnoreValues::V_false",
            "                IgnoreValues::V_empty",
            "                IgnoreValues::V_true_true",
            "                IgnoreValues::NotIgnored",
            "            WildNs::Wild",
            "                WildNs::Wild::Rows#a*",
            "                WildNs::Wild::Rows#ab",
            "                WildNs::Wild::Rows#a?c",
            "                WildNs::Wild::Rows#abc",
            "                WildNs::Wild::Rows#q\"x",
            "                WildNs::Wild::Rows#qyx",
            "                WildNs::Wild::Rows#q'x",
            "                WildNs::Wild::Light#metadataSet0",
            "                WildNs::Wild::Light#metadataSet1",
            "            WildNs::ClassRows#c*",
            "                WildNs::ClassRows#c*::M",
            "                WildNs::ClassRows#c*::N#n*",
            "                WildNs::ClassRows#c*::N#nn",
            "            WildNs::ClassRows#cd",
            "                WildNs::ClassRows#cd::M",
            "                WildNs::ClassRows#cd::N#n*",
            "                WildNs::ClassRows#cd::N#nn",
            "            TT<char>",
            "                TT<char>::M",
            "            TT<int * *>",
            "                TT<int * *>::M",
            "            TT<int *>",
            "                TT<int *>::M",
            "",
        };
    }

}
