// This file has been added for TAEF support.

using System;
using System.Text;
using System.Text.RegularExpressions;

namespace TaefTestAdapter.Helpers
{
    /// <summary>
    /// Helpers for TAEF test names. A TAEF test name has the form
    /// <c>&lt;class&gt;[#&lt;class row&gt;]::&lt;method&gt;[#&lt;method row&gt;]</c>, e.g.
    /// <list type="bullet">
    /// <item><c>Ns::Class::Method</c>, <c>Class::Method</c> (class in the global namespace),
    /// <c>Ns::Templ&lt;class std::vector&lt;int,class std::allocator&lt;int&gt; &gt; &gt;::Method</c> (class template instance),
    /// <c>`anonymous-namespace'::Class::Method</c> (anonymous namespace);</item>
    /// <item><c>Ns::Class::Method#metadataSet0</c> (lightweight data-driven row), <c>Ns::Class::Method#0</c> or
    /// <c>Ns::Class::Method#Row Name</c> (table data-driven row; row names may contain any characters, including
    /// <c>::</c>, <c>#</c>, <c>'</c>, spaces and brackets);</item>
    /// <item><c>Ns::Class#metadataSet0::Method</c>, <c>Ns::Class#0::Method</c>, <c>Class#Row Name::Method</c> (tests of a
    /// data-driven class; TE.exe lists the class as <c>Ns::Class#metadataSet0</c>), possibly combined with a method row
    /// (<c>Ns::Class#metadataSet0::Method#metadataSet1</c>);</item>
    /// <item><c>Ns::Class::Method#error</c> and <c>Ns::Class#error</c> (pseudo tests TE.exe reports if the data source
    /// of a data-driven method or class can not be loaded).</item>
    /// </list>
    /// <para>
    /// The <em>base name</em> of a test is the C++ name of its test method (<c>&lt;class&gt;::&lt;method&gt;</c>, i.e. the
    /// name without any data row suffixes). The <em>class name</em> is the class as listed by TE.exe (including a class
    /// row suffix). Only <c>::</c> outside of template arguments (<c>&lt;...&gt;</c>) separate scopes.
    /// </para>
    /// <para>
    /// Some names of data-driven tests are ambiguous since row names may contain <c>::</c>: a <c>#</c> is considered
    /// to start a class row if it is followed by a row name, <c>::</c> and an identifier (the method name) which ends
    /// the name or is followed by <c>#</c>, and if either the part before the <c>#</c> contains no <c>::</c> (a test
    /// always belongs to a class) or the row name is one generated by TAEF (<c>metadataSet&lt;n&gt;</c> or a row index).
    /// Thus, <c>Class::Method#a::b</c> is a data row <c>a::b</c> of method <c>Class::Method</c>, while
    /// <c>Class#a::b::Method</c> and <c>Ns::Class#0::Method</c> are tests of data-driven classes. Tests of data-driven
    /// classes with named rows within a namespace (<c>Ns::Class#Row::Method</c>) can not be told apart from method rows
    /// and are treated as such.
    /// </para>
    /// </summary>
    public static class TaefNames
    {
        private const string ScopeSeparator = TaefConstants.ScopeSeparator;
        private const char DataRowSeparator = TaefConstants.DataRowSeparator;

        private static readonly Regex GeneratedRowNameRegex = new Regex(@"^(?:metadataSet\d+|\d+)$", RegexOptions.Compiled | RegexOptions.CultureInvariant);

        /// <returns>
        /// The C++ name of the test method, i.e. the name without data row suffixes, e.g. <c>Ns::Class::Method</c> for
        /// <c>Ns::Class::Method#metadataSet0</c> and for <c>Ns::Class#metadataSet0::Method#1</c>.
        /// </returns>
        public static string GetBaseName(string taefName)
        {
            NameParts parts = Parse(taefName);
            return parts.ClassBase.Length == 0 ? parts.Method : parts.ClassBase + ScopeSeparator + parts.Method;
        }

        /// <returns>
        /// The data row suffix without the leading <c>#</c>, or null if the test is not data-driven: the method row
        /// (e.g. <c>metadataSet0</c>, <c>0</c> or <c>with::colons [x]</c> for <c>Class::Method#with::colons [x]</c>), the class row
        /// (<c>metadataSet0</c> for <c>Class#metadataSet0::Method</c>) or, if both exist, the class row and the method row
        /// joined by <c>#</c> (<c>metadataSet0#1</c> for <c>Class#metadataSet0::Method#1</c>).
        /// </returns>
        public static string GetDataSuffix(string taefName)
        {
            NameParts parts = Parse(taefName);
            if (parts.ClassRow == null)
                return parts.MethodRow;
            if (parts.MethodRow == null)
                return parts.ClassRow;
            return parts.ClassRow + DataRowSeparator + parts.MethodRow;
        }

        /// <returns>
        /// The class name including namespaces and the class row of data-driven classes, i.e. the class as listed by
        /// TE.exe: <c>A::B</c> for <c>A::B::M#x::y</c>, <c>Ns::Templ&lt;std::string&gt;</c> for <c>Ns::Templ&lt;std::string&gt;::M</c>,
        /// <c>Ns::Class#metadataSet0</c> for <c>Ns::Class#metadataSet0::M</c>. Returns "" if the name contains no class.
        /// </returns>
        public static string GetClassName(string taefName)
        {
            NameParts parts = Parse(taefName);
            return parts.ClassRow == null ? parts.ClassBase : parts.ClassBase + DataRowSeparator + parts.ClassRow;
        }

        /// <returns>
        /// The method name without data row suffix (<c>M</c> for <c>A::B::M#x::y</c> and for <c>A::B#0::M</c>), or the base
        /// name if the name contains no class.
        /// </returns>
        public static string GetMethodName(string taefName)
        {
            return Parse(taefName).Method;
        }

        /// <returns>
        /// The fully qualified name reported to VS: scopes are separated by <c>.</c> instead of <c>::</c> (but not within
        /// template arguments), data row suffixes (including <c>#</c>) are kept unchanged. Examples:
        /// <c>Ns::Class::Method#a::b</c> becomes <c>Ns.Class.Method#a::b</c>;
        /// <c>Ns::Templ&lt;std::string&gt;::M</c> becomes <c>Ns.Templ&lt;std::string&gt;.M</c>;
        /// <c>Ns::Class#a::b::M#0</c> becomes <c>Ns.Class#a::b.M#0</c>.
        /// </returns>
        public static string ToVsFullyQualifiedName(string taefName)
        {
            NameParts parts = Parse(taefName);

            var result = new StringBuilder(taefName.Length);
            if (parts.ClassBase.Length > 0)
            {
                AppendWithDotsAsScopeSeparators(result, parts.ClassBase);
                if (parts.ClassRow != null)
                    result.Append(DataRowSeparator).Append(parts.ClassRow);
                result.Append('.');
            }
            AppendWithDotsAsScopeSeparators(result, parts.Method);
            if (parts.MethodRow != null)
                result.Append(DataRowSeparator).Append(parts.MethodRow);

            return result.ToString();
        }

        /// <returns>The name with every single quote doubled, as required within a quoted value of a TE.exe <c>/select</c> query.</returns>
        public static string EscapeForSelect(string name)
        {
            if (name == null)
                throw new ArgumentNullException(nameof(name));

            return name.Replace("'", "''");
        }

        /// <returns>
        /// True if the name is a pseudo test TE.exe reports if the data source of a data-driven method or class can not
        /// be loaded (the name ends with <c>#error</c>).
        /// </returns>
        public static bool IsDataSourceErrorPseudoTest(string taefName)
        {
            if (taefName == null)
                throw new ArgumentNullException(nameof(taefName));

            return taefName.EndsWith(TaefConstants.DataSourceErrorSuffix, StringComparison.Ordinal);
        }

        #region Parsing

        private struct NameParts
        {
            /// <summary>Class name without class row, "" if there is no class</summary>
            public string ClassBase;
            /// <summary>Row of a data-driven class (without '#'), or null</summary>
            public string ClassRow;
            public string Method;
            /// <summary>Row of a data-driven method (without '#'), or null</summary>
            public string MethodRow;
        }

        private static NameParts Parse(string taefName)
        {
            if (taefName == null)
                throw new ArgumentNullException(nameof(taefName));

            int rowSeparatorIndex = taefName.IndexOf(DataRowSeparator);
            if (rowSeparatorIndex < 0)
                return SplitAtLastScopeSeparator(taefName, null);

            string beforeRow = taefName.Substring(0, rowSeparatorIndex);
            if (TryFindMethodAfterClassRow(taefName, rowSeparatorIndex + 1, out int methodStart, out int methodEnd))
            {
                string classRow = taefName.Substring(rowSeparatorIndex + 1, methodStart - ScopeSeparator.Length - rowSeparatorIndex - 1);
                if (LastIndexOfTopLevelScopeSeparator(beforeRow) < 0 || GeneratedRowNameRegex.IsMatch(classRow))
                {
                    return new NameParts
                    {
                        ClassBase = beforeRow,
                        ClassRow = classRow,
                        Method = taefName.Substring(methodStart, methodEnd - methodStart),
                        MethodRow = methodEnd < taefName.Length ? taefName.Substring(methodEnd + 1) : null
                    };
                }
            }

            return SplitAtLastScopeSeparator(beforeRow, taefName.Substring(rowSeparatorIndex + 1));
        }

        private static NameParts SplitAtLastScopeSeparator(string baseName, string methodRow)
        {
            int index = LastIndexOfTopLevelScopeSeparator(baseName);
            return new NameParts
            {
                ClassBase = index < 0 ? "" : baseName.Substring(0, index),
                Method = index < 0 ? baseName : baseName.Substring(index + ScopeSeparator.Length),
                MethodRow = methodRow
            };
        }

        /// <summary>
        /// Searches the text of <paramref name="name"/> starting at <paramref name="start"/> (i.e., after the first '#') for
        /// the first <c>::&lt;identifier&gt;</c> which is followed by the end of the name or by '#'.
        /// </summary>
        private static bool TryFindMethodAfterClassRow(string name, int start, out int methodStart, out int methodEnd)
        {
            for (int index = name.IndexOf(ScopeSeparator, start, StringComparison.Ordinal);
                index >= 0;
                index = name.IndexOf(ScopeSeparator, index + 1, StringComparison.Ordinal))
            {
                int identifierStart = index + ScopeSeparator.Length;
                int identifierEnd = identifierStart;
                while (identifierEnd < name.Length && IsIdentifierCharacter(name[identifierEnd]))
                    identifierEnd++;

                if (identifierEnd > identifierStart && (identifierEnd == name.Length || name[identifierEnd] == DataRowSeparator))
                {
                    methodStart = identifierStart;
                    methodEnd = identifierEnd;
                    return true;
                }
            }

            methodStart = methodEnd = -1;
            return false;
        }

        private static bool IsIdentifierCharacter(char c)
        {
            return char.IsLetterOrDigit(c) || c == '_' || c == '$';
        }

        private static int LastIndexOfTopLevelScopeSeparator(string name)
        {
            int result = -1;
            int depth = 0;
            for (int i = 0; i < name.Length; i++)
            {
                switch (name[i])
                {
                    case '<':
                        depth++;
                        break;
                    case '>':
                        if (depth > 0)
                            depth--;
                        break;
                    case ':':
                        if (depth == 0 && i + 1 < name.Length && name[i + 1] == ':')
                        {
                            result = i;
                            i++;
                        }
                        break;
                }
            }
            return result;
        }

        private static void AppendWithDotsAsScopeSeparators(StringBuilder result, string name)
        {
            int depth = 0;
            for (int i = 0; i < name.Length; i++)
            {
                char c = name[i];
                switch (c)
                {
                    case '<':
                        depth++;
                        break;
                    case '>':
                        if (depth > 0)
                            depth--;
                        break;
                    case ':':
                        if (depth == 0 && i + 1 < name.Length && name[i + 1] == ':')
                        {
                            result.Append('.');
                            i++;
                            continue;
                        }
                        break;
                }
                result.Append(c);
            }
        }

        #endregion

    }

}
