// This file has been modified for TAEF support.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using TaefTestAdapter.Common;
using TaefTestAdapter.DiaResolver;
using TaefTestAdapter.Helpers;
using TaefTestAdapter.Settings;

namespace TaefTestAdapter.TestCases
{

    /// <summary>
    /// Finds the source locations of test methods in the PDBs of a test DLL: the test methods are looked up by their
    /// exact C++ names (see <see cref="SymbolNames"/> for the differences between TAEF and PDB spellings) in the PDB of
    /// the test DLL, then in the PDBs configured by option 'Additional PDBs', and finally in the PDBs of the DLLs imported
    /// by the test DLL (if located in the test DLL's folder). Symbols are never matched by position.
    /// </summary>
    public class TestCaseResolver
    {
        /// <summary>
        /// Static member function generated by TAEF's <c>TEST_CLASS</c> / <c>BEGIN_TEST_CLASS</c> macros; its location is
        /// the location of the test class declaration.
        /// </summary>
        public const string TestClassInfoFunctionName = "TAEF_GetTestClassInfo";

        private readonly string _testDll;
        private readonly IDiaResolverFactory _diaResolverFactory;
        private readonly SettingsWrapper _settings;
        private readonly ILogger _logger;

        /// <summary>The PDB of the test DLL (available after the first lookup), or null if none has been found.</summary>
        public string TestDllPdb { get; private set; }

        public TestCaseResolver(string testDll, IDiaResolverFactory diaResolverFactory, SettingsWrapper settings, ILogger logger)
        {
            _testDll = testDll;
            _diaResolverFactory = diaResolverFactory;
            _settings = settings;
            _logger = logger;
        }

        /// <param name="functionName">The C++ name of a test method as spelled by TAEF (see <see cref="TaefNames.GetBaseName"/>).</param>
        /// <returns>The location of the test method, or null if it could not be found.</returns>
        public TestCaseLocation FindTestCaseLocation(string functionName)
        {
            FindTestCaseLocations(new[] { functionName }).TryGetValue(functionName, out TestCaseLocation location);
            return location;
        }

        /// <param name="functionNames">The C++ names of test methods as spelled by TAEF (see <see cref="TaefNames.GetBaseName"/>).</param>
        /// <returns>The locations of the test methods found, by function name.</returns>
        public IDictionary<string, TestCaseLocation> FindTestCaseLocations(IEnumerable<string> functionNames)
        {
            var result = new Dictionary<string, TestCaseLocation>();
            var unresolved = new List<string>(functionNames.Where(n => !string.IsNullOrEmpty(n)).Distinct());
            if (unresolved.Count == 0)
                return result;

            foreach (Func<IEnumerable<SymbolSource>> getSymbolSources in new Func<IEnumerable<SymbolSource>>[] { GetTestDllSymbols, GetAdditionalPdbs, GetImportedDllsSymbols })
            {
                foreach (SymbolSource symbolSource in getSymbolSources())
                {
                    int nrOfUnresolved = unresolved.Count;
                    FindTestCaseLocations(symbolSource, unresolved, result);
                    _logger.DebugInfo($"Found {nrOfUnresolved - unresolved.Count} of {nrOfUnresolved} test methods in binary '{symbolSource.Binary}', pdb '{symbolSource.Pdb}'");
                    if (unresolved.Count == 0)
                        return result;
                }
            }

            return result;
        }

        private void FindTestCaseLocations(SymbolSource symbolSource, List<string> unresolved, Dictionary<string, TestCaseLocation> result)
        {
            try
            {
                using (IDiaResolver diaResolver = _diaResolverFactory.Create(symbolSource.Binary, symbolSource.Pdb, _logger))
                {
                    FindMembersOfClasses(diaResolver, unresolved, result);
                    if (unresolved.Count > 0)
                        FindFunctionsByName(diaResolver, unresolved, result);
                    if (unresolved.Count > 0)
                        FindFunctionsInAnonymousNamespaces(diaResolver, unresolved, result);
                }
            }
            catch (Exception e)
            {
                _logger.DebugError($"Exception while resolving test locations in binary '{symbolSource.Binary}', pdb '{symbolSource.Pdb}':{Environment.NewLine}{e}");
            }
        }

        /// <summary>
        /// Looks up the classes of the test methods and locates the test methods among their members (fast, but does not
        /// work for classes within anonymous namespaces).
        /// </summary>
        private void FindMembersOfClasses(IDiaResolver diaResolver, List<string> unresolved, Dictionary<string, TestCaseLocation> result)
        {
            var functionsByClass = unresolved
                .GroupBy(TaefNames.GetClassName)
                .Where(g => g.Key.Length > 0)
                .ToList();

            foreach (IGrouping<string, string> functionsOfClass in functionsByClass)
            {
                var functionsByMember = functionsOfClass.ToDictionary(TaefNames.GetMethodName);
                foreach (string typeName in SymbolNames.GetTypeNameCandidates(functionsOfClass.Key))
                {
                    IDictionary<string, SourceFileLocation> members = diaResolver.FindMemberFunctions(typeName, functionsByMember.Keys.ToList());
                    foreach (KeyValuePair<string, SourceFileLocation> member in members)
                    {
                        if (functionsByMember.TryGetValue(member.Key, out string functionName))
                        {
                            Add(result, functionName, member.Value);
                            functionsByMember.Remove(member.Key);
                        }
                    }

                    if (functionsByMember.Count == 0)
                        break;
                }
            }

            unresolved.RemoveAll(result.ContainsKey);
        }

        private void FindFunctionsByName(IDiaResolver diaResolver, List<string> unresolved, Dictionary<string, TestCaseLocation> result)
        {
            foreach (string functionName in unresolved)
            {
                foreach (string candidate in SymbolNames.GetFunctionNameCandidates(functionName))
                {
                    SourceFileLocation location = diaResolver.FindFunctions(candidate).FirstOrDefault();
                    if (location != null)
                    {
                        Add(result, functionName, location);
                        break;
                    }
                }
            }

            unresolved.RemoveAll(result.ContainsKey);
        }

        /// <summary>
        /// Functions within nested anonymous namespaces are named like <c>A0x94c2b18a::`anonymous namespace'::Class::Method</c>
        /// in the PDB. They are found by searching for <c>*::Class::Method</c> and comparing the normalized names.
        /// </summary>
        private void FindFunctionsInAnonymousNamespaces(IDiaResolver diaResolver, List<string> unresolved, Dictionary<string, TestCaseLocation> result)
        {
            var candidatesByPattern = new Dictionary<string, IList<SourceFileLocation>>();
            foreach (string functionName in unresolved.Where(SymbolNames.ContainsAnonymousNamespace))
            {
                string pattern = "*" + TaefConstants.ScopeSeparator + SymbolNames.GetPartAfterLastAnonymousNamespace(functionName);
                if (!candidatesByPattern.TryGetValue(pattern, out IList<SourceFileLocation> candidates))
                    candidatesByPattern.Add(pattern, candidates = diaResolver.GetFunctions(pattern));

                string normalizedName = SymbolNames.Normalize(functionName);
                SourceFileLocation location = candidates.FirstOrDefault(c => SymbolNames.Normalize(c.Symbol) == normalizedName);
                if (location != null)
                    Add(result, functionName, location);
            }

            unresolved.RemoveAll(result.ContainsKey);
        }

        private void Add(Dictionary<string, TestCaseLocation> result, string functionName, SourceFileLocation location)
        {
            _logger.VerboseInfo($"Test method '{functionName}' found: {location}");
            result[functionName] = new TestCaseLocation(location.Symbol, location.Sourcefile, location.Line);
        }

        #region Symbol sources

        private class SymbolSource
        {
            public string Binary { get; }
            public string Pdb { get; }

            public SymbolSource(string binary, string pdb)
            {
                Binary = binary;
                Pdb = pdb;
            }
        }

        private IEnumerable<SymbolSource> GetTestDllSymbols()
        {
            TestDllPdb = FindPdbFile(_testDll);
            if (TestDllPdb != null)
                yield return new SymbolSource(_testDll, TestDllPdb);
        }

        private IEnumerable<SymbolSource> GetAdditionalPdbs()
        {
            foreach (string pdbPattern in _settings.GetAdditionalPdbs(_testDll))
            {
                var matchingFiles = Utils.GetMatchingFiles(pdbPattern, _logger);
                if (matchingFiles.Length == 0)
                {
                    _logger.LogWarning($"Additional PDB pattern '{pdbPattern}' does not match any files");
                    continue;
                }

                _logger.DebugInfo($"Additional PDB pattern '{pdbPattern}' matches {matchingFiles.Length} files");
                foreach (string pdbCandidate in matchingFiles)
                {
                    yield return new SymbolSource(_testDll, pdbCandidate);
                }
            }
        }

        private IEnumerable<SymbolSource> GetImportedDllsSymbols()
        {
            string testDllDirectory = Path.GetDirectoryName(_testDll);
            if (testDllDirectory == null)
                yield break;

            foreach (string import in PeParser.ParseImports(_testDll, _logger))
            {
                string importedBinary = Path.Combine(testDllDirectory, import);
                if (!File.Exists(importedBinary))
                    continue;

                string pdb = FindPdbFile(importedBinary);
                if (pdb != null)
                    yield return new SymbolSource(importedBinary, pdb);
            }
        }

        private string FindPdbFile(string binary)
        {
            string pdb = PdbLocator.FindPdbFile(binary, _settings.GetPathExtension(_testDll), _logger);
            if (pdb == null)
                _logger.DebugWarning($"No .pdb file found for '{binary}'");
            return pdb;
        }

        #endregion

    }

}
